<?php
/**
 * @file
 * us_courts_defaults_bankruptcy.features.content.inc
 */

/**
 * Implementation of hook_content_defaults().
 */
function us_courts_defaults_bankruptcy_content_defaults() {
$content = array();
$content['office_of_the_us_trustee'] = (object)array(
  'exported_path' => 'office-us-trustee',
 /* 'link' => array(
    'menu_name' => 'main-menu',
    'link_path' => 'node-name/office_of_the_us_trustee',
    'router_path' => 'node/%',
    'link_title' => 'Office of the US Trustee',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '-43',
    'identifier' => 'main-menu:node-name/office_of_the_us_trustee',
  ),  */
  'title' => 'Office of the US Trustee',
  'status' => '1',
  'promote' => '0',
  'sticky' => '0',
  'type' => 'page',
  'language' => 'und',
  'created' => '1316032821',
  'comment' => '1',
  'translate' => '0',
  'machine_name' => 'office_of_the_us_trustee',
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Nulla vitae elit libero, a pharetra augue. Vestibulum id ligula porta felis euismod semper. Donec id elit non mi porta gravida at eget metus. &nbsp; Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Donec ullamcorper nulla non metus auctor fringilla. Maecenas faucibus mollis interdum. Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Maecenas faucibus mollis interdum. Integer posuere erat a ante venenatis dapibus posuere velit aliquet.</p>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_value' => '<p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Nulla vitae elit libero, a pharetra augue. Vestibulum id ligula porta felis euismod semper. Donec id elit non mi porta gravida at eget metus.   Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Donec ullamcorper nulla non metus auctor fringilla. Maecenas faucibus mollis interdum. Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Maecenas faucibus mollis interdum. Integer posuere erat a ante venenatis dapibus posuere velit aliquet.</p>
',
        'safe_summary' => '',
      ),
    ),
  ),
);
$content['understanding_bankruptcy'] = (object)array(
  'exported_path' => 'understanding-bankruptcy',
/*  'link' => array(
    'menu_name' => 'main-menu',
    'link_path' => 'node-name/understanding_bankruptcy',
    'router_path' => 'node/%',
    'link_title' => 'Understanding Bankruptcy',
    'options' => array(
      'attributes' => array(),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '-50',
    'identifier' => 'main-menu:node-name/understanding_bankruptcy',
  ), */
  'title' => 'Understanding Bankruptcy',
  'status' => '1',
  'promote' => '0',
  'sticky' => '0',
  'type' => 'page',
  'language' => 'und',
  'created' => '1316032666',
  'comment' => '1',
  'translate' => '0',
  'machine_name' => 'understanding_bankruptcy',
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Bankruptcy is a set of federal laws and rules that can help  individuals and businesses who owe more debt than they can pay. Each of the 94 federal judicial  districts handles bankruptcy matters, and in almost all districts, bankruptcy  cases are filed in the bankruptcy court. Bankruptcy cases cannot be filed in  state court. Bankruptcy laws help people who can no longer pay their creditors  get a fresh start by liquidating their assets to pay their debts, or by  creating a repayment plan.</p>
<p>  Bankruptcy laws also protect troubled  businesses and provide for orderly distributions to business creditors through  reorganization or liquidation. These procedures are covered under Title 11 of  the United States Code (the Bankruptcy Code). The vast majority of cases are  filed under the three main chapters of the Bankruptcy Code, which are Chapter  7, Chapter 11, and Chapter 13.</p>
<p>  Federal courts have exclusive  jurisdiction over bankruptcy cases. This means that a bankruptcy case cannot be  filed in a state court.</p>
<p>  The primary purposes of the law of bankruptcy are:</p>
<ul>
  <li>to give an honest debtor a &quot;fresh start&quot; in life by  relieving the debtor of most debts, and </li>
  <li>to repay creditors in an orderly manner to the extent that the  debtor has property available for payment. </li>
</ul>
<p>Some bankruptcy cases are filed to allow a debtor to reorganize  and establish a plan to repay creditors, while other cases involve liquidation  of the debtor\'s property.</p>
<p>  A bankruptcy case normally begins by  the debtor filing a petition with the bankruptcy court. A petition may be filed  by an individual, by a husband and wife together, or by a corporation or other  entity. The debtor is also required to file statements listing assets, income,  liabilities, and the names and addresses of all creditors and how much they are  owed. The filing of the petition automatically prevents, or &quot;stays,&quot;  debt collection actions against the debtor and the debtor\'s property. As long  as the stay remains in effect, creditors cannot bring or continue lawsuits, make  wage garnishments, or even make telephone calls demanding payment. </p>
 <p> Creditors receive notice from the  clerk of court that the debtor has filed a bankruptcy petition. Some bankruptcy  cases are filed to allow a debtor to reorganize and establish a plan to repay  creditors, while other cases involve liquidation of the debtor\'s property. In  many bankruptcy cases involving liquidation of the property of individual  consumers, there is little or no money available from the debtor\'s estate to  pay creditors. As a result, in these cases there are few issues or disputes,  and the debtor is normally granted a &quot;discharge&quot; of most debts  without objection. This means that the debtor will no longer be personally  liable for repaying the debts.</p>
<p>  In other cases, however, disputes may  give rise to litigation in a bankruptcy case over such matters as who owns  certain property, how it should be used, what the property is worth, how much  is owed on a debt, whether the debtor should be discharged from certain debts,  or how much money should be paid to lawyers, accountants, auctioneers, or other  professionals. Litigation in the bankruptcy court is conducted in much the same  way that civil cases are handled in the district court. There may be discovery,  pretrial proceedings, settlement efforts, and a trial. </p>
<p><em>[Other suggested content and/or links  to content:</em></p>
<ul>
  <li><em>Pro se filing</em></li>
  <li><em>Bankruptcy FAQs</em></li>
  <li><em>Bankruptcy Basics</em></li>
  <li><em>Link to Court Directory</em></li>
  <li><em>Glossary of Bankruptcy Terms</em></li>
  <li><em>Links to other resources on the site  for pro se filers]</em></li>
</ul>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_value' => '<p>Bankruptcy is a set of federal laws and rules that can help  individuals and businesses who owe more debt than they can pay. Each of the 94 federal judicial  districts handles bankruptcy matters, and in almost all districts, bankruptcy  cases are filed in the bankruptcy court. Bankruptcy cases cannot be filed in  state court. Bankruptcy laws help people who can no longer pay their creditors  get a fresh start by liquidating their assets to pay their debts, or by  creating a repayment plan.</p>
<p>  Bankruptcy laws also protect troubled  businesses and provide for orderly distributions to business creditors through  reorganization or liquidation. These procedures are covered under Title 11 of  the United States Code (the Bankruptcy Code). The vast majority of cases are  filed under the three main chapters of the Bankruptcy Code, which are Chapter  7, Chapter 11, and Chapter 13.</p>
<p>  Federal courts have exclusive  jurisdiction over bankruptcy cases. This means that a bankruptcy case cannot be  filed in a state court.</p>
<p>  The primary purposes of the law of bankruptcy are:</p>
<ul>
  <li>to give an honest debtor a &quot;fresh start&quot; in life by  relieving the debtor of most debts, and </li>
  <li>to repay creditors in an orderly manner to the extent that the  debtor has property available for payment. </li>
</ul>
<p>Some bankruptcy cases are filed to allow a debtor to reorganize  and establish a plan to repay creditors, while other cases involve liquidation  of the debtor\'s property.</p>
<p>  A bankruptcy case normally begins by  the debtor filing a petition with the bankruptcy court. A petition may be filed  by an individual, by a husband and wife together, or by a corporation or other  entity. The debtor is also required to file statements listing assets, income,  liabilities, and the names and addresses of all creditors and how much they are  owed. The filing of the petition automatically prevents, or &quot;stays,&quot;  debt collection actions against the debtor and the debtor\'s property. As long  as the stay remains in effect, creditors cannot bring or continue lawsuits, make  wage garnishments, or even make telephone calls demanding payment. </p>
 <p> Creditors receive notice from the  clerk of court that the debtor has filed a bankruptcy petition. Some bankruptcy  cases are filed to allow a debtor to reorganize and establish a plan to repay  creditors, while other cases involve liquidation of the debtor\'s property. In  many bankruptcy cases involving liquidation of the property of individual  consumers, there is little or no money available from the debtor\'s estate to  pay creditors. As a result, in these cases there are few issues or disputes,  and the debtor is normally granted a &quot;discharge&quot; of most debts  without objection. This means that the debtor will no longer be personally  liable for repaying the debts.</p>
<p>  In other cases, however, disputes may  give rise to litigation in a bankruptcy case over such matters as who owns  certain property, how it should be used, what the property is worth, how much  is owed on a debt, whether the debtor should be discharged from certain debts,  or how much money should be paid to lawyers, accountants, auctioneers, or other  professionals. Litigation in the bankruptcy court is conducted in much the same  way that civil cases are handled in the district court. There may be discovery,  pretrial proceedings, settlement efforts, and a trial. </p>
<p><em>[Other suggested content and/or links  to content:</em></p>
<ul>
  <li><em>Pro se filing</em></li>
  <li><em>Bankruptcy FAQs</em></li>
  <li><em>Bankruptcy Basics</em></li>
  <li><em>Link to Court Directory</em></li>
  <li><em>Glossary of Bankruptcy Terms</em></li>
  <li><em>Links to other resources on the site  for pro se filers]</em></li>
</ul>
',
        'safe_summary' => '',
      ),
    ),
  ),
);
return $content;
}
